# Generated by Django 3.0.4 on 2020-03-24 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(max_length=200),
        ),
    ]
